name: Build and publish api image

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/gobot

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build ./droneInterface --file ./droneInterface/Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ github.event.release.tag_name }}

    
    - name: Log in to the Container registry
      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' 
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Push Docker image
      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' 
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ github.event.release.tag_name }}
